Import data

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

Load data and break it into labels and images for testing, training and verification

In [25]:
flowers = tfds.load("oxford_flowers102")
training = flowers["train"]
training_images = np.array([item["image"].numpy() for item in training])
training_labels = np.array([item["label"] for item in training])
print(training_images[0])

C:\Users\connc\AppData\Local\Temp\ipykernel_22556\1152688827.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  training_images = np.array([item["image"].numpy() for item in training])


[[[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 2 0]
  [1 2 0]
  [1 2 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [6 7 2]
  [6 7 2]
  [5 6 1]]]


In [3]:
testing = flowers["test"]
testing_images = np.array([item["image"] for item in testing])
testing_labels = np.array([item["label"] for item in testing])
print(testing_labels[0])

C:\Users\connc\AppData\Local\Temp\ipykernel_22556\160554485.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  testing_images = np.array([item["image"] for item in testing])


40


In [4]:
validation = flowers["validation"]
validation_images = np.array([item["image"] for item in validation])
validation_labels = np.array([item["label"] for item in validation])
print(validation_labels[0])

C:\Users\connc\AppData\Local\Temp\ipykernel_22556\2325856267.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  validation_images = np.array([item["image"] for item in validation])


88


For all the image arrays, create 3 seperate arrays for Red, Green and Blue pixels, divided by 255 if RGB values are used

In [31]:
training_images = [np.resize(image/255.0,1196032) for image in training_images]
print(training_images[0])

[1.53787005e-05 3.07574010e-05 0.00000000e+00 ... 4.61361015e-05
 0.00000000e+00 3.07574010e-05]


In [ ]:
testing_images = [np.resize(image/255.0,1196032) for image in testing_images]
print(testing_images[0])

In [ ]:
validation_images = [np.resize(image/255.0,1196032) for image in validation_images]
print(validation_images[0])

Reshape the data so it fits any image size

Create Network Model

Train Model

Test Model