Import data

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

Load data and break it into labels and images for testing, training and verification

In [10]:
flowers = tfds.load("oxford_flowers102")
training = flowers["train"]

training_images = []
training_labels = []

for item in training:
    training_images.append(item["image"].numpy()/255.0)
    training_labels.append(item["label"].numpy()/255.0)

print(training_images[0])

[[[0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 [[0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 [[0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  [0.00392157 0.00784314 0.        ]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 ...

 [[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.02352941 0.02745098 0.00784314]
  [0.02352941 0.02745098 0.00784314]
  [0.01960784 0.02352941 0.00392157]]

 [[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]


In [11]:
testing = flowers["test"]

testing_images = []
testing_labels = []

for item in testing:
    testing_images.append(item["image"].numpy()/255.0)
    testing_labels.append(item["label"].numpy()/255.0)

print(testing_labels[0])

MemoryError: Unable to allocate 7.63 MiB for an array with shape (500, 667, 3) and data type float64

In [ ]:
validation = flowers["validation"]
validation_images = np.array([item["image"].numpy()/255.0 for item in validation])
validation_labels = np.array([item["label"] for item in validation])
print(validation_labels[0])

C:\Users\connc\AppData\Local\Temp\ipykernel_22556\1685638850.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  validation_images = np.array([item["image"].numpy() for item in validation])


88


For all the image arrays, reshape them and divide them by 255

In [ ]:
#training_images = [np.resize(image/255.0,1196032) for image in training_images]
print(training_images[0])

MemoryError: Unable to allocate 9.12 MiB for an array with shape (1196032,) and data type float64

In [ ]:
#testing_images = [np.resize(image/255.0,1196032) for image in testing_images]
print(testing_images[0])

MemoryError: Unable to allocate 15.3 MiB for an array with shape (2001000,) and data type float64

In [ ]:
#validation_images = [np.resize(image/255.0,1196032) for image in validation_images]
print(validation_images[0])

Create Network Model

In [ ]:
model = tf.keras.models.Sequential([ 
  tf.keras.layers.InputLayer(input_shape=1196032, dtype=float), 
  tf.keras.layers.Dense(128, activation='relu'), 
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(testing_labels.max) 
])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'builtin_function_or_method'

Train Model

Test Model